name: 'edqm_project'
version: '1.0.0'
config-version: 2


profile: 'edqm_snowflake'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by 'dbt clean'
  - "target"
  - "dbt_packages"

models:
  edqm_project:
    # Config for all models
    staging:
      +materialized: view
      +schema: STAGING
    marts:
      +materialized: table
      +schema: MARTS

vars:
  # Elementary variables (optional overrides)
  elementary:
    edr_cli_run: true
